# Generated by Django 4.0.3 on 2022-05-22 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tiendas', '0003_cierre_caja'),
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes', models.IntegerField(default=20)),
                ('cuotas', models.IntegerField(default=20)),
                ('plazo', models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual'), ('Anual', 'Anual')], default='Diario', max_length=10)),
                ('comentario', models.CharField(blank=True, max_length=100)),
                ('estado_venta', models.CharField(choices=[('Vigente', 'Vigente'), ('Vencido', 'Vencido'), ('Pagado', 'Pagado'), ('Perdida', 'Perdida')], default='Vigente', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tiendas.tienda')),
            ],
        ),
    ]
