# Generated by Django 4.1 on 2022-10-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_alter_venta_plazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_vencimiento',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
