# Generated by Django 4.1 on 2022-10-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_alter_venta_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='saldo_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
