# Generated by Django 4.1 on 2022-10-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0005_alter_venta_saldo_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='saldo_actual',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
