# Generated by Django 4.1 on 2022-10-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0006_alter_venta_saldo_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='valor_venta',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
