# Generated by Django 4.1 on 2022-11-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0007_alter_venta_valor_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado_venta',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('Vencido', 'Vencido'), ('Pagado', 'Pagado'), ('Perdida', 'Perdida'), ('Atrasado', 'Atrasado')], default='Vigente', max_length=10),
        ),
    ]
