<<<<<<< HEAD
# Generated by Django 4.1 on 2023-09-06 13:52
=======
# Generated by Django 4.1 on 2023-08-30 19:58
>>>>>>> 2293f83054eb96f13e24356a494b1f6372cb58e9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0008_alter_venta_estado_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='saldo_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='valor_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
