# Generated by Django 4.1 on 2023-08-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0008_alter_venta_estado_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='saldo_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='valor_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
