# Generated by Django 4.0.3 on 2022-06-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Trabajadores', '0001_initial'),
        ('Ventas', '0002_alter_venta_plazo'),
        ('Tiendas', '0005_remove_historicaltienda_administrador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recaudo', models.DateField()),
                ('valor_recaudo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tiendas.tienda')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trabajadores.perfil')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.venta')),
            ],
        ),
    ]
