# Generated by Django 4.1 on 2022-10-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recaudos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recaudo',
            name='trabajador',
        ),
    ]
