# Generated by Django 4.1 on 2022-11-01 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recaudos', '0002_remove_recaudo_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita_Blanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_falla', models.CharField(choices=[('Casa o Local Cerrado', 'Casa o Local Cerrado'), ('Cliente no Tiene Dinero', 'Cliente no Tiene Dinero'), ('Cliente de Viaje', 'Cliente de Viaje'), ('Cliente no Aparece', 'Cliente no Aparece'), ('Cliente Enfermo', 'Cliente Enfermo'), ('Otro Motivo', 'Otro Motivo')], max_length=50)),
                ('comentario', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recaudo',
            name='visita_blanco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Recaudos.visita_blanco'),
        ),
    ]
