# Generated by Django 4.1 on 2022-11-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recaudos', '0004_alter_recaudo_visita_blanco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaudo',
            name='visita_blanco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Recaudos.visita_blanco'),
        ),
    ]
