# Generated by Django 4.1 on 2022-11-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recaudos', '0005_alter_recaudo_visita_blanco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaudo',
            name='valor_recaudo',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
