# Generated by Django 4.1 on 2023-09-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recaudos', '0006_alter_recaudo_valor_recaudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaudo',
            name='valor_recaudo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
