# Generated by Django 4.1 on 2026-04-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recaudos', '0007_alter_recaudo_valor_recaudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recaudo',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='precision_gps',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
