# Generated by Django 4.0.3 on 2022-03-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tiendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono_principal', models.CharField(max_length=15)),
                ('telefono_opcional', models.CharField(blank=True, max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado_cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Clientes.estado_cliente')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tiendas.tienda')),
            ],
        ),
    ]
