# Generated by Django 4.1 on 2022-11-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendas', '0005_remove_historicaltienda_administrador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='moneda',
        ),
        migrations.AlterField(
            model_name='cierre_caja',
            name='valor',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='caja_inicial',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Moneda',
        ),
    ]
