# Generated by Django 4.1 on 2022-12-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendas', '0007_remove_tienda_ciudad_delete_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Prueba', 'Prueba'), ('Mensual', 'Mensual'), ('Anual', 'Anual')], max_length=100)),
                ('precio', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda_Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_activacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Vencida', 'Vencida'), ('Pendiente Pago', 'Pendiente Pago')], default='Activa', max_length=50)),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tiendas.membresia')),
                ('tienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tiendas.tienda')),
            ],
        ),
    ]
