# Generated by Django 4.0.3 on 2022-05-22 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tiendas', '0002_alter_tienda_fecha_registro'),
        ('Trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentario', models.CharField(blank=True, max_length=100)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tiendas.tienda')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trabajadores.perfil')),
            ],
        ),
    ]
