# Generated by Django 4.1 on 2022-11-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0002_gasto_trabajador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='valor',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
