# Generated by Django 4.1 on 2023-09-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilidades', '0003_alter_utilidad_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilidad',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
